### ISSUE TITLE
CORS rejection on `auction/act` POST

### ISSUE THREAD

**Issue by AttwellBrian** [AttwellBrian/nico#24]

**Comment by AttwellBrian** [comment]
Waiting on johnson to push a branch that reproduces the issue before digging into this.

**Comment by johnsonfung** [comment]
The `frontEndwork` branch has now rebased to your latest updates and has the reproduced issue.

To reproduce:
1. Open two separately cached windows (chrome and safair, e.g.)
2. Join as two users, and then start game (I guess one user could work too)
3. Go to the user that is currently the active user and click "Power plant market" on the right
4. Click on any of the bid buttons. Look at console.

The API call is located on line 280 of `/frontend/src/functions.js`
